remote_theme: nathanclevenger/landing
title: Landing.Page.as - Beautiful Landing Pages on GitHub Pages
description: 
icon: 
logo: 
hero:
  title:
    - Line 1
    - Line 2
  description: Discover the types of APIs that can change everything.
logos:
  - SaaS.Dev:
    logo: 
    link: https://saas.dev
footer:
  social:
    twitter: https://twitter.com/drivly
    linkedin: https://twitter.com/drivly
    github: https://twitter.com/drivly
  links:
    - Solutions:
      - Marketing: https://marketing.page.as
    - Support:
      - Pricing: https://marketing.page.as
      - Documentation: https://marketing.page.as
      - Guides: https://marketing.page.as
      - API Status: https://marketing.page.as
    - Company:
      - About: https://marketing.page.as
      - Blog: https://marketing.page.as
      - Jobs: https://marketing.page.as
      - Partners: https://marketing.page.as
    - Legal:
      - Privacy: https://marketing.page.as
      - Terms: https://marketing.page.as
      
    
