remote_theme: nathanclevenger/landing

name: Landing.Page.as
title: Landing.Page.as - Beautiful Landing Pages on GitHub Pages
description: Beautiful Landing Pages on GitHub Pages
icon: 
logo: 
hero:
  title:
    - Line 1
    - Line 2
  description: Discover the types of APIs that can change everything.
logos:
  - SaaS.Dev:
      logo: 
      link: https://saas.dev
  - API.Mt:
      logo: 
      link: https://api.mt
footer:
  social:
    twitter: https://twitter.com/drivly
    linkedin: https://linkedin.com/drivly
    github: https://github.com/drivly
  links:
    - Solutions:
      - Marketing: https://marketing.page.as
      - Analytics: https://analytics.page.as
      - Commerce: https://commerce.page.as
      - Insights: https://insights.page.as
    - Support:
      - Pricing: https://pricing.page.as
      - Documentation: https://documentation.page.as
      - Guides: https://guide.page.as
      - API Status: https://api.status.page.as
    - Company:
      - About: https://about.page.as
      - Blog: https://blogs.as
      - Jobs: https://jobs.page.as
      - Partners: https://partner.page.as
    - Legal:
      - Privacy: https://privacy.page.as
      - Terms: https://terms.page.as
