remote_theme: nathanclevenger/landing

name: Landing.Page.as
title: Beautiful Landing Pages on GitHub Pages
description: Get your next big idea launched in seconds with a beautiful open-source landing page template for GitHub Pages.
icon: 🚀
theme:
  color: indigo
  darkMode: false
  font: Inter
logo: 
hero:
  callout: 
    name: NEW
    text: Landing.Page.as is now released! Check it out now
  title: Beautiful Landing Pages on GitHub Pages
  description: Get your next big idea launched in seconds with a beautiful open-source landing page template for GitHub Pages.
  cta:
    primary: 
      text: Get Started
      link: {{ site.github.repo_url }}
    secondary: 
      text: Learn More
      link: #features
logos:
  - SaaS.Dev:
      logo: 
      link: https://saas.dev
  - API.Mt:
      logo: 
      link: https://api.mt
benefits:
  Beautiful Design:
    description:
    code: 
  Easy to Code:
    description:
    code: 
footer:
  social:
    twitter: https://twitter.com/nateclev
    linkedin: https://www.linkedin.com/in/nathanclevenger/
    github: https://github.com/nathanclevenger
  links:
    Solutions:
      Marketing: https://marketing.page.as
      Analytics: https://analytics.page.as
      Commerce: https://commerce.page.as
      Insights: https://insights.page.as
    Support:
      Pricing: https://pricing.page.as
      Documentation: https://documentation.page.as
      Guides: https://guide.page.as
      Status: https://status.page.as
    Company:
      About: https://about.page.as
      Blog: https://blogs.as
      Jobs: https://jobs.page.as
      Partners: https://partner.page.as
    Legal:
      Privacy: https://privacy.page.as
      Terms: https://terms.page.as
